import { Adjective, CategoryType } from './types';

export const ADJECTIVES_DATA: Adjective[] = [
  // --- Внешность и размер ---
  {
    id: 'alto',
    spanishMasculine: 'alto',
    spanishFeminine: 'alta',
    spanishPluralMasculine: 'altos',
    spanishPluralFeminine: 'altas',
    russian: 'высокий',
    russianFeminine: 'высокая',
    russianPlural: 'высокие',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'bajo',
    exampleEs: 'Mi hermano es muy alto.',
    exampleRu: 'Мой брат очень высокий.',
    ruleNote: 'Окончание -o меняется на -a в женском роде.'
  },
  {
    id: 'bajo',
    spanishMasculine: 'bajo',
    spanishFeminine: 'baja',
    spanishPluralMasculine: 'bajos',
    spanishPluralFeminine: 'bajas',
    russian: 'низкий',
    russianFeminine: 'низкая',
    russianPlural: 'низкие',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'alto',
    exampleEs: 'Esta mesa es bastante baja.',
    exampleRu: 'Этот стол достаточно низкий.',
    ruleNote: 'Окончание -o меняется на -a.'
  },
  {
    id: 'grande',
    spanishMasculine: 'grande',
    spanishFeminine: 'grande',
    spanishPluralMasculine: 'grandes',
    spanishPluralFeminine: 'grandes',
    russian: 'большой',
    russianFeminine: 'большая',
    russianPlural: 'большие',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'pequeno',
    exampleEs: 'Esa casa es muy grande.',
    exampleRu: 'Тот дом очень большой.',
    ruleNote: 'Окончание -e одинаково для мужского и женского рода! Перед сущ. сокращается до "gran".'
  },
  {
    id: 'pequeno',
    spanishMasculine: 'pequeño',
    spanishFeminine: 'pequeña',
    spanishPluralMasculine: 'pequeños',
    spanishPluralFeminine: 'pequeñas',
    russian: 'маленький',
    russianFeminine: 'маленькая',
    russianPlural: 'маленькие',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'grande',
    exampleEs: 'El perro es pequeño y divertido.',
    exampleRu: 'Собака маленькая и забавная.',
  },
  {
    id: 'guapo',
    spanishMasculine: 'guapo',
    spanishFeminine: 'guapa',
    spanishPluralMasculine: 'guapos',
    spanishPluralFeminine: 'guapas',
    russian: 'красивый',
    russianFeminine: 'красивая',
    russianPlural: 'красивые',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'feo',
    exampleEs: 'El actor es guapo.',
    exampleRu: 'Актер красивый.',
  },
  {
    id: 'feo',
    spanishMasculine: 'feo',
    spanishFeminine: 'fea',
    spanishPluralMasculine: 'feos',
    spanishPluralFeminine: 'feas',
    russian: 'некрасивый',
    russianFeminine: 'некрасивая',
    russianPlural: 'некрасивые',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'guapo',
    exampleEs: 'El monstruo es feo.',
    exampleRu: 'Монстр некрасивый.',
  },
  {
    id: 'delgado',
    spanishMasculine: 'delgado',
    spanishFeminine: 'delgada',
    spanishPluralMasculine: 'delgados',
    spanishPluralFeminine: 'delgadas',
    russian: 'худой',
    russianFeminine: 'худая',
    russianPlural: 'худые',
    category: 'Внешность и размер',
    difficulty: 'medium',
    antonymId: 'gordo',
    exampleEs: 'Ella es bastante delgada.',
    exampleRu: 'Она довольно худая.',
  },
  {
    id: 'gordo',
    spanishMasculine: 'gordo',
    spanishFeminine: 'gorda',
    spanishPluralMasculine: 'gordos',
    spanishPluralFeminine: 'gordas',
    russian: 'толстый',
    russianFeminine: 'толстая',
    russianPlural: 'толстые',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'delgado',
    exampleEs: 'El gato gordo duerme todo el día.',
    exampleRu: 'Толстый кот спит весь день.',
  },
  {
    id: 'joven',
    spanishMasculine: 'joven',
    spanishFeminine: 'joven',
    spanishPluralMasculine: 'jóvenes',
    spanishPluralFeminine: 'jóvenes',
    russian: 'молодой',
    russianFeminine: 'молодая',
    russianPlural: 'молодые',
    category: 'Внешность и размер',
    difficulty: 'medium',
    antonymId: 'viejo',
    exampleEs: 'La profesora es joven.',
    exampleRu: 'Учительница молодая.',
    ruleNote: 'Прилагательные на согласный (кроме -or) не меняются по роду. Во мн. ч. появляется ударение: jóvenes.'
  },
  {
    id: 'viejo',
    spanishMasculine: 'viejo',
    spanishFeminine: 'vieja',
    spanishPluralMasculine: 'viejos',
    spanishPluralFeminine: 'viejas',
    russian: 'старый',
    russianFeminine: 'старая',
    russianPlural: 'старые',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'joven',
    exampleEs: 'Este libro es viejo.',
    exampleRu: 'Эта книга старая.',
  },
  {
    id: 'largo',
    spanishMasculine: 'largo',
    spanishFeminine: 'larga',
    spanishPluralMasculine: 'largos',
    spanishPluralFeminine: 'largas',
    russian: 'длинный',
    russianFeminine: 'длинная',
    russianPlural: 'длинные',
    category: 'Внешность и размер',
    difficulty: 'medium',
    antonymId: 'corto',
    exampleEs: 'Tiene un pelo largo.',
    exampleRu: 'У неё длинные волосы.',
    ruleNote: 'Внимание: largo означает ДЛИННЫЙ (а не широкий).'
  },
  {
    id: 'corto',
    spanishMasculine: 'corto',
    spanishFeminine: 'corta',
    spanishPluralMasculine: 'cortos',
    spanishPluralFeminine: 'cortas',
    russian: 'короткий',
    russianFeminine: 'короткая',
    russianPlural: 'короткие',
    category: 'Внешность и размер',
    difficulty: 'easy',
    antonymId: 'largo',
    exampleEs: 'El vestido es corto.',
    exampleRu: 'Платье короткое.',
  },
  {
    id: 'ancho',
    spanishMasculine: 'ancho',
    spanishFeminine: 'ancha',
    spanishPluralMasculine: 'anchos',
    spanishPluralFeminine: 'anchas',
    russian: 'широкий',
    russianFeminine: 'широкая',
    russianPlural: 'широкие',
    category: 'Внешность и размер',
    difficulty: 'medium',
    antonymId: 'estrecho',
    exampleEs: 'La calle es muy ancha.',
    exampleRu: 'Улица очень широкая.',
  },
  {
    id: 'estrecho',
    spanishMasculine: 'estrecho',
    spanishFeminine: 'estrecha',
    spanishPluralMasculine: 'estrechos',
    spanishPluralFeminine: 'estrechas',
    russian: 'узкий',
    russianFeminine: 'узкая',
    russianPlural: 'узкие',
    category: 'Внешность и размер',
    difficulty: 'medium',
    antonymId: 'ancho',
    exampleEs: 'El camino es estrecho.',
    exampleRu: 'Тропинка узкая.',
  },

  // --- Характер и ум ---
  {
    id: 'inteligente',
    spanishMasculine: 'inteligente',
    spanishFeminine: 'inteligente',
    spanishPluralMasculine: 'inteligentes',
    spanishPluralFeminine: 'inteligentes',
    russian: 'умный',
    russianFeminine: 'умная',
    russianPlural: 'умные',
    category: 'Характер и ум',
    difficulty: 'easy',
    antonymId: 'tonto',
    exampleEs: 'Mis alumnos son muy inteligentes.',
    exampleRu: 'Мои ученики очень умные.',
    ruleNote: 'Окончание -e подходит и для мужского, и для женского рода.'
  },
  {
    id: 'tonto',
    spanishMasculine: 'tonto',
    spanishFeminine: 'tonta',
    spanishPluralMasculine: 'tontos',
    spanishPluralFeminine: 'tontas',
    russian: 'глупый',
    russianFeminine: 'глупая',
    russianPlural: 'глупые',
    category: 'Характер и ум',
    difficulty: 'easy',
    antonymId: 'inteligente',
    exampleEs: 'No seas tonto, por favor.',
    exampleRu: 'Не будь глупым, пожалуйста.',
  },
  {
    id: 'simpatico',
    spanishMasculine: 'simpático',
    spanishFeminine: 'simpática',
    spanishPluralMasculine: 'simpáticos',
    spanishPluralFeminine: 'simpáticas',
    russian: 'симпатичный / приятный',
    russianFeminine: 'симпатичная',
    russianPlural: 'симпатичные',
    category: 'Характер и ум',
    difficulty: 'easy',
    antonymId: 'antipatico',
    exampleEs: 'Ana es una chica muy simpática.',
    exampleRu: 'Ана — очень приятная девушка.',
  },
  {
    id: 'antipatico',
    spanishMasculine: 'antipático',
    spanishFeminine: 'antipática',
    spanishPluralMasculine: 'antipáticos',
    spanishPluralFeminine: 'antipáticas',
    russian: 'неприятный / неприятен в общении',
    russianFeminine: 'неприятная',
    russianPlural: 'неприятные',
    category: 'Характер и ум',
    difficulty: 'medium',
    antonymId: 'simpatico',
    exampleEs: 'El camarero era bastante antipático.',
    exampleRu: 'Официант был довольно неприятным.',
  },
  {
    id: 'trabajador',
    spanishMasculine: 'trabajador',
    spanishFeminine: 'trabajadora',
    spanishPluralMasculine: 'trabajadores',
    spanishPluralFeminine: 'trabajadoras',
    russian: 'трудолюбивый',
    russianFeminine: 'трудолюбивая',
    russianPlural: 'трудолюбивые',
    category: 'Характер и ум',
    difficulty: 'medium',
    antonymId: 'perezoso',
    exampleEs: 'Es un hombre muy trabajador.',
    exampleRu: 'Он очень трудолюбивый мужчина.',
    ruleNote: 'Прилагательные на -or добавляют -a в женском роде (trabajadora).'
  },
  {
    id: 'perezoso',
    spanishMasculine: 'perezoso',
    spanishFeminine: 'perezosa',
    spanishPluralMasculine: 'perezosos',
    spanishPluralFeminine: 'perezosas',
    russian: 'ленивый',
    russianFeminine: 'ленивая',
    russianPlural: 'ленивые',
    category: 'Характер и ум',
    difficulty: 'medium',
    antonymId: 'trabajador',
    exampleEs: 'Hoy me siento un poco perezoso.',
    exampleRu: 'Сегодня я чувствую себя немного ленивым.',
  },
  {
    id: 'amable',
    spanishMasculine: 'amable',
    spanishFeminine: 'amable',
    spanishPluralMasculine: 'amables',
    spanishPluralFeminine: 'amables',
    russian: 'любезный / вежливый',
    russianFeminine: 'любезная',
    russianPlural: 'любезные',
    category: 'Характер и ум',
    difficulty: 'medium',
    exampleEs: 'Gracias, eres muy amable.',
    exampleRu: 'Спасибо, вы очень любезны.',
    ruleNote: 'Окончание -e неизменно по роду.'
  },
  {
    id: 'sincero',
    spanishMasculine: 'sincero',
    spanishFeminine: 'sincera',
    spanishPluralMasculine: 'sinceros',
    spanishPluralFeminine: 'sinceras',
    russian: 'искренний',
    russianFeminine: 'искренняя',
    russianPlural: 'искренние',
    category: 'Характер и ум',
    difficulty: 'medium',
    exampleEs: 'Es una respuesta sincera.',
    exampleRu: 'Это искренний ответ.',
  },
  {
    id: 'paciente',
    spanishMasculine: 'paciente',
    spanishFeminine: 'paciente',
    spanishPluralMasculine: 'pacientes',
    spanishPluralFeminine: 'pacientes',
    russian: 'терпеливый',
    russianFeminine: 'терпеливая',
    russianPlural: 'терпеливые',
    category: 'Характер и ум',
    difficulty: 'medium',
    antonymId: 'impaciente',
    exampleEs: 'Un buen médico es paciente.',
    exampleRu: 'Хороший врач терпелив.',
  },
  {
    id: 'generoso',
    spanishMasculine: 'generoso',
    spanishFeminine: 'generosa',
    spanishPluralMasculine: 'generosos',
    spanishPluralFeminine: 'generosas',
    russian: 'щедрый',
    russianFeminine: 'щедрая',
    russianPlural: 'щедрые',
    category: 'Характер и ум',
    difficulty: 'easy',
    antonymId: 'tacanho',
    exampleEs: 'Es muy generoso con sus amigos.',
    exampleRu: 'Он очень щедр со своими друзьями.',
  },

  // --- Эмоции и состояние ---
  {
    id: 'feliz',
    spanishMasculine: 'feliz',
    spanishFeminine: 'feliz',
    spanishPluralMasculine: 'felices',
    spanishPluralFeminine: 'felices',
    russian: 'счастливый',
    russianFeminine: 'счастливая',
    russianPlural: 'счастливые',
    category: 'Эмоции и состояние',
    difficulty: 'easy',
    antonymId: 'triste',
    exampleEs: '¡Estoy muy feliz de verte!',
    exampleRu: 'Я очень счастлив тебя видеть!',
    ruleNote: 'Во множественном числе -z меняется на -ces: felices.'
  },
  {
    id: 'triste',
    spanishMasculine: 'triste',
    spanishFeminine: 'triste',
    spanishPluralMasculine: 'tristes',
    spanishPluralFeminine: 'tristes',
    russian: 'грустный',
    russianFeminine: 'грустная',
    russianPlural: 'грустные',
    category: 'Эмоции и состояние',
    difficulty: 'easy',
    antonymId: 'feliz',
    exampleEs: '¿Por qué estás triste hoy?',
    exampleRu: 'Почему ты грустный сегодня?',
  },
  {
    id: 'cansado',
    spanishMasculine: 'cansado',
    spanishFeminine: 'cansada',
    spanishPluralMasculine: 'cansados',
    spanishPluralFeminine: 'cansadas',
    russian: 'уставший',
    russianFeminine: 'уставшая',
    russianPlural: 'уставшие',
    category: 'Эмоции и состояние',
    difficulty: 'easy',
    exampleEs: 'Estoy cansado después del trabajo.',
    exampleRu: 'Я уставший после работы.',
    ruleNote: 'Используется с глаголом ESTAR (временное состояние).'
  },
  {
    id: 'contento',
    spanishMasculine: 'contento',
    spanishFeminine: 'contenta',
    spanishPluralMasculine: 'contentos',
    spanishPluralFeminine: 'contentas',
    russian: 'довольный',
    russianFeminine: 'довольная',
    russianPlural: 'довольные',
    category: 'Эмоции и состояние',
    difficulty: 'easy',
    exampleEs: 'Estamos muy contentos con el resultado.',
    exampleRu: 'Мы очень довольны результатом.',
  },
  {
    id: 'enfadado',
    spanishMasculine: 'enfadado',
    spanishFeminine: 'enfadada',
    spanishPluralMasculine: 'enfadados',
    spanishPluralFeminine: 'enfadadas',
    russian: 'сердитый / злой',
    russianFeminine: 'сердитая',
    russianPlural: 'сердитые',
    category: 'Эмоции и состояние',
    difficulty: 'medium',
    exampleEs: 'El jefe está enfadado hoy.',
    exampleRu: 'Начальник сегодня сердитый.',
  },
  {
    id: 'tranquilo',
    spanishMasculine: 'tranquilo',
    spanishFeminine: 'tranquila',
    spanishPluralMasculine: 'tranquilos',
    spanishPluralFeminine: 'tranquilas',
    russian: 'спокойный',
    russianFeminine: 'спокойная',
    russianPlural: 'спокойные',
    category: 'Эмоции и состояние',
    difficulty: 'easy',
    antonymId: 'nervioso',
    exampleEs: 'Es un lugar muy tranquilo.',
    exampleRu: 'Это очень спокойное место.',
  },
  {
    id: 'nervioso',
    spanishMasculine: 'nervioso',
    spanishFeminine: 'nerviosa',
    spanishPluralMasculine: 'nerviosos',
    spanishPluralFeminine: 'nerviosas',
    russian: 'нервный / взволнованный',
    russianFeminine: 'нервная',
    russianPlural: 'нервные',
    category: 'Эмоции и состояние',
    difficulty: 'easy',
    antonymId: 'tranquilo',
    exampleEs: 'Estoy nervioso antes del examen.',
    exampleRu: 'Я нервничаю перед экзаменом.',
  },
  {
    id: 'enfermo',
    spanishMasculine: 'enfermo',
    spanishFeminine: 'enferma',
    spanishPluralMasculine: 'enfermos',
    spanishPluralFeminine: 'enfermas',
    russian: 'больной',
    russianFeminine: 'больная',
    russianPlural: 'больные',
    category: 'Эмоции и состояние',
    difficulty: 'easy',
    antonymId: 'sano',
    exampleEs: 'Juan está enfermo y no va a clase.',
    exampleRu: 'Хуан болен и не идет на занятия.',
    ruleNote: 'Используется с глаголом ESTAR (estar enfermo).'
  },
  {
    id: 'sano',
    spanishMasculine: 'sano',
    spanishFeminine: 'sana',
    spanishPluralMasculine: 'sanos',
    spanishPluralFeminine: 'sanas',
    russian: 'здоровый',
    russianFeminine: 'здоровая',
    russianPlural: 'здоровые',
    category: 'Эмоции и состояние',
    difficulty: 'easy',
    antonymId: 'enfermo',
    exampleEs: 'Comer fruta es muy sano.',
    exampleRu: 'Есть фрукты очень полезно для здоровья.',
  },

  // --- Качество и оценка ---
  {
    id: 'bueno',
    spanishMasculine: 'bueno',
    spanishFeminine: 'buena',
    spanishPluralMasculine: 'buenos',
    spanishPluralFeminine: 'buenas',
    russian: 'хороший',
    russianFeminine: 'хорошая',
    russianPlural: 'хорошие',
    category: 'Качество и оценка',
    difficulty: 'easy',
    antonymId: 'malo',
    exampleEs: 'Es un buen amigo mío.',
    exampleRu: 'Он мой хороший друг.',
    ruleNote: 'Перед существительным муж. рода ед.ч. теряет -o: "un buen amigo".'
  },
  {
    id: 'malo',
    spanishMasculine: 'malo',
    spanishFeminine: 'mala',
    spanishPluralMasculine: 'malos',
    spanishPluralFeminine: 'malas',
    russian: 'плохой',
    russianFeminine: 'плохая',
    russianPlural: 'плохие',
    category: 'Качество и оценка',
    difficulty: 'easy',
    antonymId: 'bueno',
    exampleEs: 'Es una mala idea.',
    exampleRu: 'Это плохая идея.',
    ruleNote: 'Перед сущ. муж. рода сокращается до "mal": "un mal día".'
  },
  {
    id: 'facil',
    spanishMasculine: 'fácil',
    spanishFeminine: 'fácil',
    spanishPluralMasculine: 'fáciles',
    spanishPluralFeminine: 'fáciles',
    russian: 'легкий / простой',
    russianFeminine: 'легкая',
    russianPlural: 'легкие',
    category: 'Качество и оценка',
    difficulty: 'easy',
    antonymId: 'dificil',
    exampleEs: 'El examen de español es fácil.',
    exampleRu: 'Экзамен по испанскому лёгкий.',
    ruleNote: 'Мн.ч. добавляет -es (fáciles).'
  },
  {
    id: 'dificil',
    spanishMasculine: 'difícil',
    spanishFeminine: 'difícil',
    spanishPluralMasculine: 'difíciles',
    spanishPluralFeminine: 'difíciles',
    russian: 'трудный / сложный',
    russianFeminine: 'трудная',
    russianPlural: 'трудные',
    category: 'Качество и оценка',
    difficulty: 'easy',
    antonymId: 'facil',
    exampleEs: 'No es una decisión difícil.',
    exampleRu: 'Это не сложное решение.',
  },
  {
    id: 'caro',
    spanishMasculine: 'caro',
    spanishFeminine: 'cara',
    spanishPluralMasculine: 'caros',
    spanishPluralFeminine: 'caras',
    russian: 'дорогой (по цене)',
    russianFeminine: 'дорогая',
    russianPlural: 'дорогие',
    category: 'Качество и оценка',
    difficulty: 'easy',
    antonymId: 'barato',
    exampleEs: 'Este coche es muy caro.',
    exampleRu: 'Эта машина очень дорогая.',
  },
  {
    id: 'barato',
    spanishMasculine: 'barato',
    spanishFeminine: 'barata',
    spanishPluralMasculine: 'baratos',
    spanishPluralFeminine: 'baratas',
    russian: 'дешевый',
    russianFeminine: 'дешевая',
    russianPlural: 'дешевые',
    category: 'Качество и оценка',
    difficulty: 'easy',
    antonymId: 'caro',
    exampleEs: 'Los billetes de avión son baratos.',
    exampleRu: 'Авиабилеты дешёвые.',
  },
  {
    id: 'nuevo',
    spanishMasculine: 'nuevo',
    spanishFeminine: 'nueva',
    spanishPluralMasculine: 'nuevos',
    spanishPluralFeminine: 'nuevas',
    russian: 'новый',
    russianFeminine: 'новая',
    russianPlural: 'новые',
    category: 'Качество и оценка',
    difficulty: 'easy',
    antonymId: 'viejo',
    exampleEs: 'Tengo un teléfono nuevo.',
    exampleRu: 'У меня новый телефон.',
  },
  {
    id: 'util',
    spanishMasculine: 'útil',
    spanishFeminine: 'útil',
    spanishPluralMasculine: 'útiles',
    spanishPluralFeminine: 'útiles',
    russian: 'полезный',
    russianFeminine: 'полезная',
    russianPlural: 'полезные',
    category: 'Качество и оценка',
    difficulty: 'medium',
    exampleEs: 'El diccionario es muy útil.',
    exampleRu: 'Словарь очень полезный.',
  },
  {
    id: 'importante',
    spanishMasculine: 'importante',
    spanishFeminine: 'importante',
    spanishPluralMasculine: 'importantes',
    spanishPluralFeminine: 'importantes',
    russian: 'важный',
    russianFeminine: 'важная',
    russianPlural: 'важные',
    category: 'Качество и оценка',
    difficulty: 'easy',
    exampleEs: 'Es una regla muy importante.',
    exampleRu: 'Это очень важное правило.',
  },
  {
    id: 'fuerte',
    spanishMasculine: 'fuerte',
    spanishFeminine: 'fuerte',
    spanishPluralMasculine: 'fuertes',
    spanishPluralFeminine: 'fuertes',
    russian: 'сильный',
    russianFeminine: 'сильная',
    russianPlural: 'сильные',
    category: 'Качество и оценка',
    difficulty: 'medium',
    antonymId: 'debil',
    exampleEs: 'El viento es muy fuerte.',
    exampleRu: 'Ветер очень сильный.',
  },
  {
    id: 'debil',
    spanishMasculine: 'débil',
    spanishFeminine: 'débil',
    spanishPluralMasculine: 'débiles',
    spanishPluralFeminine: 'débiles',
    russian: 'слабый',
    russianFeminine: 'слабая',
    russianPlural: 'слабые',
    category: 'Качество и оценка',
    difficulty: 'medium',
    antonymId: 'fuerte',
    exampleEs: 'Se siente débil hoy.',
    exampleRu: 'Он чувствует себя слабым сегодня.',
  },

  // --- Время и скорость ---
  {
    id: 'rapido',
    spanishMasculine: 'rápido',
    spanishFeminine: 'rápida',
    spanishPluralMasculine: 'rápidos',
    spanishPluralFeminine: 'rápidas',
    russian: 'быстрый',
    russianFeminine: 'быстрая',
    russianPlural: 'быстрые',
    category: 'Время и скорость',
    difficulty: 'easy',
    antonymId: 'lento',
    exampleEs: 'El tren de alta velocidad es muy rápido.',
    exampleRu: 'Скоростной поезд очень быстрый.',
  },
  {
    id: 'lento',
    spanishMasculine: 'lento',
    spanishFeminine: 'lenta',
    spanishPluralMasculine: 'lentos',
    spanishPluralFeminine: 'lentas',
    russian: 'медленный',
    russianFeminine: 'медленная',
    russianPlural: 'медленные',
    category: 'Время и скорость',
    difficulty: 'easy',
    antonymId: 'rapido',
    exampleEs: 'La tortuga es muy lenta.',
    exampleRu: 'Черепаха очень медленная.',
  },
  {
    id: 'temprano',
    spanishMasculine: 'temprano',
    spanishFeminine: 'temprana',
    spanishPluralMasculine: 'tempranos',
    spanishPluralFeminine: 'tempranas',
    russian: 'ранний',
    russianFeminine: 'ранняя',
    russianPlural: 'ранние',
    category: 'Время и скорость',
    difficulty: 'medium',
    antonymId: 'tardio',
    exampleEs: 'Es un vuelo temprano.',
    exampleRu: 'Это ранний рейс.',
  },

  // --- Погода и природа ---
  {
    id: 'caliente',
    spanishMasculine: 'caliente',
    spanishFeminine: 'caliente',
    spanishPluralMasculine: 'calientes',
    spanishPluralFeminine: 'calientes',
    russian: 'горячий',
    russianFeminine: 'горячая',
    russianPlural: 'горячие',
    category: 'Погода и природа',
    difficulty: 'easy',
    antonymId: 'frio',
    exampleEs: 'El café está muy caliente.',
    exampleRu: 'Кофе очень горячий.',
  },
  {
    id: 'frio',
    spanishMasculine: 'frío',
    spanishFeminine: 'fría',
    spanishPluralMasculine: 'fríos',
    spanishPluralFeminine: 'frías',
    russian: 'холодный',
    russianFeminine: 'холодная',
    russianPlural: 'холодные',
    category: 'Погода и природа',
    difficulty: 'easy',
    antonymId: 'caliente',
    exampleEs: 'El agua del mar está fría.',
    exampleRu: 'Вода в море холодная.',
  },
  {
    id: 'seco',
    spanishMasculine: 'seco',
    spanishFeminine: 'seca',
    spanishPluralMasculine: 'secos',
    spanishPluralFeminine: 'secas',
    russian: 'сухой',
    russianFeminine: 'сухая',
    russianPlural: 'сухие',
    category: 'Погода и природа',
    difficulty: 'medium',
    antonymId: 'mojado',
    exampleEs: 'El clima aquí es muy seco.',
    exampleRu: 'Климат здесь очень сухой.',
  },
  {
    id: 'mojado',
    spanishMasculine: 'mojado',
    spanishFeminine: 'mojada',
    spanishPluralMasculine: 'mojados',
    spanishPluralFeminine: 'mojadas',
    russian: 'мокрый',
    russianFeminine: 'мокрая',
    russianPlural: 'мокрые',
    category: 'Погода и природа',
    difficulty: 'medium',
    antonymId: 'seco',
    exampleEs: 'El suelo está mojado por la lluvia.',
    exampleRu: 'Пол мокрый от дождя.',
  },

  // --- Цвета и ощущения ---
  {
    id: 'rojo',
    spanishMasculine: 'rojo',
    spanishFeminine: 'roja',
    spanishPluralMasculine: 'rojos',
    spanishPluralFeminine: 'rojas',
    russian: 'красный',
    russianFeminine: 'красная',
    russianPlural: 'красные',
    category: 'Цвета и ощущения',
    difficulty: 'easy',
    exampleEs: 'Me gusta la manzana roja.',
    exampleRu: 'Мне нравится красное яблоко.',
  },
  {
    id: 'azul',
    spanishMasculine: 'azul',
    spanishFeminine: 'azul',
    spanishPluralMasculine: 'azules',
    spanishPluralFeminine: 'azules',
    russian: 'синий / голубой',
    russianFeminine: 'синяя',
    russianPlural: 'синие',
    category: 'Цвета и ощущения',
    difficulty: 'easy',
    exampleEs: 'El cielo está totalmente azul.',
    exampleRu: 'Небо абсолютно синее.',
    ruleNote: 'Прилагательное на согласный -l не имеет женской формы.'
  },
  {
    id: 'verde',
    spanishMasculine: 'verde',
    spanishFeminine: 'verde',
    spanishPluralMasculine: 'verdes',
    spanishPluralFeminine: 'verdes',
    russian: 'зеленый',
    russianFeminine: 'зеленая',
    russianPlural: 'зеленые',
    category: 'Цвета и ощущения',
    difficulty: 'easy',
    exampleEs: 'La hierba es verde.',
    exampleRu: 'Трава зелёная.',
  },
  {
    id: 'blanco',
    spanishMasculine: 'blanco',
    spanishFeminine: 'blanca',
    spanishPluralMasculine: 'blancos',
    spanishPluralFeminine: 'blancas',
    russian: 'белый',
    russianFeminine: 'белая',
    russianPlural: 'белые',
    category: 'Цвета и ощущения',
    difficulty: 'easy',
    antonymId: 'negro',
    exampleEs: 'La nieve es blanca.',
    exampleRu: 'Снег белый.',
  },
  {
    id: 'negro',
    spanishMasculine: 'negro',
    spanishFeminine: 'negra',
    spanishPluralMasculine: 'negros',
    spanishPluralFeminine: 'negras',
    russian: 'черный',
    russianFeminine: 'черная',
    russianPlural: 'черные',
    category: 'Цвета и ощущения',
    difficulty: 'easy',
    antonymId: 'blanco',
    exampleEs: 'Tiene un gato negro.',
    exampleRu: 'У неё черный кот.',
  },
  {
    id: 'dulce',
    spanishMasculine: 'dulce',
    spanishFeminine: 'dulce',
    spanishPluralMasculine: 'dulces',
    spanishPluralFeminine: 'dulces',
    russian: 'сладкий',
    russianFeminine: 'сладкая',
    russianPlural: 'сладкие',
    category: 'Цвета и ощущения',
    difficulty: 'easy',
    exampleEs: 'Este pastel está muy dulce.',
    exampleRu: 'Этот торт очень сладкий.',
  }
];

export const CATEGORIES: CategoryType[] = [
  'Внешность и размер',
  'Характер и ум',
  'Эмоции и состояние',
  'Качество и оценка',
  'Погода и природа',
  'Цвета и ощущения',
  'Время и скорость'
];
